name: Deploy Portfolio and Weather to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            portfolio-site/portfolio-site/package-lock.json
            weather/weather-app/package-lock.json

      # -------------------------
      # Build Portfolio
      # -------------------------

      - name: Install Portfolio dependencies
        working-directory: ./portfolio-site/portfolio-site
        run: npm ci

      - name: Build Portfolio
        working-directory: ./portfolio-site/portfolio-site
        run: npm run build

      # -------------------------
      # Build Weather App
      # -------------------------

      - name: Install Weather dependencies
        working-directory: ./weather/weather-app
        run: npm ci

      - name: Build Weather App
        working-directory: ./weather/weather-app
        run: npm run build

      # -------------------------
      # Put Weather inside Portfolio
      # -------------------------

      - name: Copy Weather into Portfolio
        run: |
          mkdir -p portfolio-site/portfolio-site/dist/weather
          cp -r weather/weather-app/dist/* portfolio-site/portfolio-site/dist/weather/

      # -------------------------
      # GitHub Pages
      # -------------------------

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./portfolio-site/portfolio-site/dist

  deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
